/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import dplusplus.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseASimplesAlterableDecl(ASimplesAlterableDecl node);
    void caseASimplesUnalterableDecl(ASimplesUnalterableDecl node);
    void caseAExprRelacional(AExprRelacional node);
    void caseAIgualdadeRelacional(AIgualdadeRelacional node);
    void caseAFatorExpr(AFatorExpr node);
    void caseASomaExpr(ASomaExpr node);
    void caseAMenosExpr(AMenosExpr node);
    void caseATermoFator(ATermoFator node);
    void caseAMultFator(AMultFator node);
    void caseADivFator(ADivFator node);
    void caseARealTermo(ARealTermo node);
    void caseAInteiroTermo(AInteiroTermo node);
    void caseAIdTermo(AIdTermo node);
    void caseAParTermo(AParTermo node);

    void caseTTAlterable(TTAlterable node);
    void caseTTUnalterable(TTUnalterable node);
    void caseTTReal(TTReal node);
    void caseTTInteiro(TTInteiro node);
    void caseTTId(TTId node);
    void caseTTSoma(TTSoma node);
    void caseTTMenos(TTMenos node);
    void caseTTMult(TTMult node);
    void caseTTDiv(TTDiv node);
    void caseTTIgual(TTIgual node);
    void caseTTParEsq(TTParEsq node);
    void caseTTParDir(TTParDir node);
    void caseTTVirgula(TTVirgula node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTWhitespace(TWhitespace node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
