/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesAlterableDecl(ASimplesAlterableDecl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesUnalterableDecl(ASimplesUnalterableDecl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExprRelacional(AExprRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualdadeRelacional(AIgualdadeRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFatorExpr(AFatorExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpr(ASomaExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosExpr(AMenosExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATermoFator(ATermoFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultFator(AMultFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivFator(ADivFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealTermo(ARealTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroTermo(AInteiroTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdTermo(AIdTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParTermo(AParTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAlterable(TTAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTUnalterable(TTUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTReal(TTReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTInteiro(TTInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTId(TTId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTSoma(TTSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMenos(TTMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMult(TTMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTDiv(TTDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTIgual(TTIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTParEsq(TTParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTParDir(TTParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTVirgula(TTVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhitespace(TWhitespace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
