/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import dplusplus.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTTFamily(TTFamily node);
    void caseTTDerivesFrom(TTDerivesFrom node);
    void caseTTStart(TTStart node);
    void caseTTFinish(TTFinish node);
    void caseTTObject(TTObject node);
    void caseTTAlterable(TTAlterable node);
    void caseTTUnalterable(TTUnalterable node);
    void caseTTAnswer(TTAnswer node);
    void caseTTNumber(TTNumber node);
    void caseTTYes(TTYes node);
    void caseTTNo(TTNo node);
    void caseTTProcedure(TTProcedure node);
    void caseTTFunction(TTFunction node);
    void caseTTInCaseThat(TTInCaseThat node);
    void caseTTOtherwise(TTOtherwise node);
    void caseTTAsLongAs(TTAsLongAs node);
    void caseTTAnd(TTAnd node);
    void caseTTOr(TTOr node);
    void caseTTIf(TTIf node);
    void caseTTElse(TTElse node);
    void caseTTEntryPoint(TTEntryPoint node);
    void caseTTId(TTId node);
    void caseTTIdClasse(TTIdClasse node);
    void caseTTReal(TTReal node);
    void caseTTInteiro(TTInteiro node);
    void caseTTAssign(TTAssign node);
    void caseTTSoma(TTSoma node);
    void caseTTMenos(TTMenos node);
    void caseTTMult(TTMult node);
    void caseTTDiv(TTDiv node);
    void caseTTIgual(TTIgual node);
    void caseTTMenor(TTMenor node);
    void caseTTMaior(TTMaior node);
    void caseTTNot(TTNot node);
    void caseTTPonto(TTPonto node);
    void caseTTParEsq(TTParEsq node);
    void caseTTParDir(TTParDir node);
    void caseTTColEsq(TTColEsq node);
    void caseTTColDir(TTColDir node);
    void caseTTPipe(TTPipe node);
    void caseTTEcomercial(TTEcomercial node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTInicioComentarioBloco(TInicioComentarioBloco node);
    void caseTConteudoComentario(TConteudoComentario node);
    void caseTFimComentarioBloco(TFimComentarioBloco node);
    void caseTWhitespace(TWhitespace node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
