/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseTTFamily(TTFamily node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTDerivesFrom(TTDerivesFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTStart(TTStart node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTFinish(TTFinish node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTObject(TTObject node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAlterable(TTAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTUnalterable(TTUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAnswer(TTAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTNumber(TTNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTYes(TTYes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTNo(TTNo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTProcedure(TTProcedure node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTFunction(TTFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTInCaseThat(TTInCaseThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTOtherwise(TTOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAsLongAs(TTAsLongAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAnd(TTAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTOr(TTOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTIf(TTIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTElse(TTElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTEntryPoint(TTEntryPoint node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTId(TTId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTIdClasse(TTIdClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTReal(TTReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTInteiro(TTInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTAssign(TTAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTSoma(TTSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMenos(TTMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMult(TTMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTDiv(TTDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTIgual(TTIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMenor(TTMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTMaior(TTMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTNot(TTNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTPonto(TTPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTParEsq(TTParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTParDir(TTParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTColEsq(TTColEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTColDir(TTColDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTPipe(TTPipe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTEcomercial(TTEcomercial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInicioComentarioBloco(TInicioComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConteudoComentario(TConteudoComentario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFimComentarioBloco(TFimComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhitespace(TWhitespace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
