/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPDecl().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inASimplesAlterableDecl(ASimplesAlterableDecl node)
    {
        defaultIn(node);
    }

    public void outASimplesAlterableDecl(ASimplesAlterableDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesAlterableDecl(ASimplesAlterableDecl node)
    {
        inASimplesAlterableDecl(node);
        if(node.getTAlterable() != null)
        {
            node.getTAlterable().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outASimplesAlterableDecl(node);
    }

    public void inASimplesUnalterableDecl(ASimplesUnalterableDecl node)
    {
        defaultIn(node);
    }

    public void outASimplesUnalterableDecl(ASimplesUnalterableDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesUnalterableDecl(ASimplesUnalterableDecl node)
    {
        inASimplesUnalterableDecl(node);
        if(node.getTUnalterable() != null)
        {
            node.getTUnalterable().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outASimplesUnalterableDecl(node);
    }

    public void inAExprRelacional(AExprRelacional node)
    {
        defaultIn(node);
    }

    public void outAExprRelacional(AExprRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprRelacional(AExprRelacional node)
    {
        inAExprRelacional(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprRelacional(node);
    }

    public void inAIgualdadeRelacional(AIgualdadeRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualdadeRelacional(AIgualdadeRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualdadeRelacional(AIgualdadeRelacional node)
    {
        inAIgualdadeRelacional(node);
        if(node.getRelacional() != null)
        {
            node.getRelacional().apply(this);
        }
        if(node.getTIgual() != null)
        {
            node.getTIgual().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAIgualdadeRelacional(node);
    }

    public void inAFatorExpr(AFatorExpr node)
    {
        defaultIn(node);
    }

    public void outAFatorExpr(AFatorExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorExpr(AFatorExpr node)
    {
        inAFatorExpr(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAFatorExpr(node);
    }

    public void inASomaExpr(ASomaExpr node)
    {
        defaultIn(node);
    }

    public void outASomaExpr(ASomaExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpr(ASomaExpr node)
    {
        inASomaExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getTSoma() != null)
        {
            node.getTSoma().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outASomaExpr(node);
    }

    public void inAMenosExpr(AMenosExpr node)
    {
        defaultIn(node);
    }

    public void outAMenosExpr(AMenosExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExpr(AMenosExpr node)
    {
        inAMenosExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getTMenos() != null)
        {
            node.getTMenos().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAMenosExpr(node);
    }

    public void inATermoFator(ATermoFator node)
    {
        defaultIn(node);
    }

    public void outATermoFator(ATermoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermoFator(ATermoFator node)
    {
        inATermoFator(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATermoFator(node);
    }

    public void inAMultFator(AMultFator node)
    {
        defaultIn(node);
    }

    public void outAMultFator(AMultFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultFator(AMultFator node)
    {
        inAMultFator(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        if(node.getTMult() != null)
        {
            node.getTMult().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMultFator(node);
    }

    public void inADivFator(ADivFator node)
    {
        defaultIn(node);
    }

    public void outADivFator(ADivFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivFator(ADivFator node)
    {
        inADivFator(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        if(node.getTDiv() != null)
        {
            node.getTDiv().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outADivFator(node);
    }

    public void inARealTermo(ARealTermo node)
    {
        defaultIn(node);
    }

    public void outARealTermo(ARealTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTermo(ARealTermo node)
    {
        inARealTermo(node);
        if(node.getTReal() != null)
        {
            node.getTReal().apply(this);
        }
        outARealTermo(node);
    }

    public void inAInteiroTermo(AInteiroTermo node)
    {
        defaultIn(node);
    }

    public void outAInteiroTermo(AInteiroTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroTermo(AInteiroTermo node)
    {
        inAInteiroTermo(node);
        if(node.getTInteiro() != null)
        {
            node.getTInteiro().apply(this);
        }
        outAInteiroTermo(node);
    }

    public void inAIdTermo(AIdTermo node)
    {
        defaultIn(node);
    }

    public void outAIdTermo(AIdTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdTermo(AIdTermo node)
    {
        inAIdTermo(node);
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        outAIdTermo(node);
    }

    public void inAParTermo(AParTermo node)
    {
        defaultIn(node);
    }

    public void outAParTermo(AParTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParTermo(AParTermo node)
    {
        inAParTermo(node);
        if(node.getTParEsq() != null)
        {
            node.getTParEsq().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getTParDir() != null)
        {
            node.getTParDir().apply(this);
        }
        outAParTermo(node);
    }
}
