/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AIgualdadeRelacional extends PRelacional
{
    private PRelacional _relacional_;
    private TTIgual _tIgual_;
    private PExpr _expr_;

    public AIgualdadeRelacional()
    {
        // Constructor
    }

    public AIgualdadeRelacional(
        @SuppressWarnings("hiding") PRelacional _relacional_,
        @SuppressWarnings("hiding") TTIgual _tIgual_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setRelacional(_relacional_);

        setTIgual(_tIgual_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AIgualdadeRelacional(
            cloneNode(this._relacional_),
            cloneNode(this._tIgual_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualdadeRelacional(this);
    }

    public PRelacional getRelacional()
    {
        return this._relacional_;
    }

    public void setRelacional(PRelacional node)
    {
        if(this._relacional_ != null)
        {
            this._relacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacional_ = node;
    }

    public TTIgual getTIgual()
    {
        return this._tIgual_;
    }

    public void setTIgual(TTIgual node)
    {
        if(this._tIgual_ != null)
        {
            this._tIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tIgual_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacional_)
            + toString(this._tIgual_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacional_ == child)
        {
            this._relacional_ = null;
            return;
        }

        if(this._tIgual_ == child)
        {
            this._tIgual_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relacional_ == oldChild)
        {
            setRelacional((PRelacional) newChild);
            return;
        }

        if(this._tIgual_ == oldChild)
        {
            setTIgual((TTIgual) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
