/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultFator extends PFator
{
    private PFator _fator_;
    private TTMult _tMult_;
    private PTermo _termo_;

    public AMultFator()
    {
        // Constructor
    }

    public AMultFator(
        @SuppressWarnings("hiding") PFator _fator_,
        @SuppressWarnings("hiding") TTMult _tMult_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setFator(_fator_);

        setTMult(_tMult_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new AMultFator(
            cloneNode(this._fator_),
            cloneNode(this._tMult_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultFator(this);
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    public TTMult getTMult()
    {
        return this._tMult_;
    }

    public void setTMult(TTMult node)
    {
        if(this._tMult_ != null)
        {
            this._tMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tMult_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator_)
            + toString(this._tMult_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        if(this._tMult_ == child)
        {
            this._tMult_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        if(this._tMult_ == oldChild)
        {
            setTMult((TTMult) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
