/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AParTermo extends PTermo
{
    private TTParEsq _tParEsq_;
    private PExpr _expr_;
    private TTParDir _tParDir_;

    public AParTermo()
    {
        // Constructor
    }

    public AParTermo(
        @SuppressWarnings("hiding") TTParEsq _tParEsq_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TTParDir _tParDir_)
    {
        // Constructor
        setTParEsq(_tParEsq_);

        setExpr(_expr_);

        setTParDir(_tParDir_);

    }

    @Override
    public Object clone()
    {
        return new AParTermo(
            cloneNode(this._tParEsq_),
            cloneNode(this._expr_),
            cloneNode(this._tParDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParTermo(this);
    }

    public TTParEsq getTParEsq()
    {
        return this._tParEsq_;
    }

    public void setTParEsq(TTParEsq node)
    {
        if(this._tParEsq_ != null)
        {
            this._tParEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tParEsq_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TTParDir getTParDir()
    {
        return this._tParDir_;
    }

    public void setTParDir(TTParDir node)
    {
        if(this._tParDir_ != null)
        {
            this._tParDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tParDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tParEsq_)
            + toString(this._expr_)
            + toString(this._tParDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tParEsq_ == child)
        {
            this._tParEsq_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._tParDir_ == child)
        {
            this._tParDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tParEsq_ == oldChild)
        {
            setTParEsq((TTParEsq) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._tParDir_ == oldChild)
        {
            setTParDir((TTParDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
