/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesUnalterableDecl extends PDecl
{
    private TTUnalterable _tUnalterable_;
    private PTermo _termo_;

    public ASimplesUnalterableDecl()
    {
        // Constructor
    }

    public ASimplesUnalterableDecl(
        @SuppressWarnings("hiding") TTUnalterable _tUnalterable_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setTUnalterable(_tUnalterable_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesUnalterableDecl(
            cloneNode(this._tUnalterable_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesUnalterableDecl(this);
    }

    public TTUnalterable getTUnalterable()
    {
        return this._tUnalterable_;
    }

    public void setTUnalterable(TTUnalterable node)
    {
        if(this._tUnalterable_ != null)
        {
            this._tUnalterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tUnalterable_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tUnalterable_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tUnalterable_ == child)
        {
            this._tUnalterable_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tUnalterable_ == oldChild)
        {
            setTUnalterable((TTUnalterable) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
