/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesAlterableDecl extends PDecl
{
    private TTAlterable _tAlterable_;
    private PTermo _termo_;

    public ASimplesAlterableDecl()
    {
        // Constructor
    }

    public ASimplesAlterableDecl(
        @SuppressWarnings("hiding") TTAlterable _tAlterable_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setTAlterable(_tAlterable_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesAlterableDecl(
            cloneNode(this._tAlterable_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesAlterableDecl(this);
    }

    public TTAlterable getTAlterable()
    {
        return this._tAlterable_;
    }

    public void setTAlterable(TTAlterable node)
    {
        if(this._tAlterable_ != null)
        {
            this._tAlterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tAlterable_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tAlterable_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tAlterable_ == child)
        {
            this._tAlterable_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tAlterable_ == oldChild)
        {
            setTAlterable((TTAlterable) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
