/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TFimComentarioBloco extends Token
{
    public TFimComentarioBloco()
    {
        super.setText("-}");
    }

    public TFimComentarioBloco(int line, int pos)
    {
        super.setText("-}");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimComentarioBloco(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimComentarioBloco(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimComentarioBloco text.");
    }
}
