/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TInicioComentarioBloco extends Token
{
    public TInicioComentarioBloco()
    {
        super.setText("{-");
    }

    public TInicioComentarioBloco(int line, int pos)
    {
        super.setText("{-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInicioComentarioBloco(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInicioComentarioBloco(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInicioComentarioBloco text.");
    }
}
