/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTAlterable extends Token
{
    public TTAlterable()
    {
        super.setText("alterable");
    }

    public TTAlterable(int line, int pos)
    {
        super.setText("alterable");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTAlterable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTAlterable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTAlterable text.");
    }
}
