/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTAnswer extends Token
{
    public TTAnswer()
    {
        super.setText("answer");
    }

    public TTAnswer(int line, int pos)
    {
        super.setText("answer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTAnswer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTAnswer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTAnswer text.");
    }
}
