/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTAsLongAs extends Token
{
    public TTAsLongAs()
    {
        super.setText("as long as");
    }

    public TTAsLongAs(int line, int pos)
    {
        super.setText("as long as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTAsLongAs(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTAsLongAs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTAsLongAs text.");
    }
}
