/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTDerives extends Token
{
    public TTDerives()
    {
        super.setText("derives");
    }

    public TTDerives(int line, int pos)
    {
        super.setText("derives");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTDerives(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTDerives(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTDerives text.");
    }
}
