/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTDerivesFrom extends Token
{
    public TTDerivesFrom()
    {
        super.setText("derives from");
    }

    public TTDerivesFrom(int line, int pos)
    {
        super.setText("derives from");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTDerivesFrom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTDerivesFrom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTDerivesFrom text.");
    }
}
