/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTFamily extends Token
{
    public TTFamily()
    {
        super.setText("family");
    }

    public TTFamily(int line, int pos)
    {
        super.setText("family");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTFamily(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTFamily(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTFamily text.");
    }
}
