/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTFinish extends Token
{
    public TTFinish()
    {
        super.setText("finish");
    }

    public TTFinish(int line, int pos)
    {
        super.setText("finish");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTFinish(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTFinish(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTFinish text.");
    }
}
