/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTFunction extends Token
{
    public TTFunction()
    {
        super.setText("function");
    }

    public TTFunction(int line, int pos)
    {
        super.setText("function");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTFunction(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTFunction(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTFunction text.");
    }
}
