/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTInCaseThat extends Token
{
    public TTInCaseThat()
    {
        super.setText("in case that");
    }

    public TTInCaseThat(int line, int pos)
    {
        super.setText("in case that");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTInCaseThat(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTInCaseThat(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTInCaseThat text.");
    }
}
