/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTNo extends Token
{
    public TTNo()
    {
        super.setText("no");
    }

    public TTNo(int line, int pos)
    {
        super.setText("no");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTNo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTNo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTNo text.");
    }
}
