/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTNumber extends Token
{
    public TTNumber()
    {
        super.setText("number");
    }

    public TTNumber(int line, int pos)
    {
        super.setText("number");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTNumber(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTNumber(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTNumber text.");
    }
}
