/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTObject extends Token
{
    public TTObject()
    {
        super.setText("object");
    }

    public TTObject(int line, int pos)
    {
        super.setText("object");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTObject(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTObject(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTObject text.");
    }
}
