/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTOtherwise extends Token
{
    public TTOtherwise()
    {
        super.setText("otherwise");
    }

    public TTOtherwise(int line, int pos)
    {
        super.setText("otherwise");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTOtherwise(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTOtherwise(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTOtherwise text.");
    }
}
