/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTProcedure extends Token
{
    public TTProcedure()
    {
        super.setText("procedure");
    }

    public TTProcedure(int line, int pos)
    {
        super.setText("procedure");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTProcedure(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTProcedure(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTProcedure text.");
    }
}
