/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTStart extends Token
{
    public TTStart()
    {
        super.setText("start");
    }

    public TTStart(int line, int pos)
    {
        super.setText("start");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTStart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTStart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTStart text.");
    }
}
