/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTUnalterable extends Token
{
    public TTUnalterable()
    {
        super.setText("unalterable");
    }

    public TTUnalterable(int line, int pos)
    {
        super.setText("unalterable");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTUnalterable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTUnalterable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTUnalterable text.");
    }
}
