/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TTYes extends Token
{
    public TTYes()
    {
        super.setText("yes");
    }

    public TTYes(int line, int pos)
    {
        super.setText("yes");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTYes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTYes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTYes text.");
    }
}
