/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.parser;

import dplusplus.node.*;
import dplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTAlterable(@SuppressWarnings("unused") TTAlterable node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTUnalterable(@SuppressWarnings("unused") TTUnalterable node)
    {
        this.index = 1;
    }

    @Override
    public void caseTTReal(@SuppressWarnings("unused") TTReal node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTInteiro(@SuppressWarnings("unused") TTInteiro node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTId(@SuppressWarnings("unused") TTId node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTSoma(@SuppressWarnings("unused") TTSoma node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTMenos(@SuppressWarnings("unused") TTMenos node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTMult(@SuppressWarnings("unused") TTMult node)
    {
        this.index = 7;
    }

    @Override
    public void caseTTDiv(@SuppressWarnings("unused") TTDiv node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTIgual(@SuppressWarnings("unused") TTIgual node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTParEsq(@SuppressWarnings("unused") TTParEsq node)
    {
        this.index = 10;
    }

    @Override
    public void caseTTParDir(@SuppressWarnings("unused") TTParDir node)
    {
        this.index = 11;
    }

    @Override
    public void caseTTVirgula(@SuppressWarnings("unused") TTVirgula node)
    {
        this.index = 12;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 13;
    }
}
